Configuration update
SocialFinanceDigitalLabs/liia-tools-pipeline pull request #14
Opened 2024-07-09 12:58 UTC by patrick-troy

Convert the .yml config to .json for future updates.

Use this .json during the cleaning process to make sure:
- maximum retention period applied
- PAN file restrictions applied (e.g. ad1 not to be processed)

Using the same .json during the report making process to make sure:
- only LAs that have signed up to the DPIA have their data processed
- retention applied depending on the use case e.g. 11 years PAN, 6 years SUFFICIENCY
- file restrictions applied per use case
- column restrictions applied per use case

2024-07-23 13:39 UTC, DJavur approved these changes

2024-07-24 15:44 UTC, MichaelHanksSF requested changes
Hello Patrick,

The issue that I brought to your attention earlier is an issue with the code:
Within the apply_retention() function in transform.py, this code doesn't work:
```
    for table_name in data:
        table = data[table_name].copy()
        data_container[table_name] = table[
            table[year_column] > current_year - retention_period
        ].copy()

        data_container[table_name] = table[
            table[la_column].isin(signed_las)
            ].copy()
```
Because data_container is re-referencing table.copy() for the signed_las check, it nullifies the result of the first check where it applies retention period.

By testing a modified json that should filter out 2020 files, you can see that it never does. But if you comment out lines 177-179, the code does then remove 2020 files.

2024-07-25 05:38 UTC, patrick-troy commented
> Hello Patrick,
> 
> The issue that I brought to your attention earlier is an issue with the code: Within the apply_retention() function in transform.py, this code doesn't work:
> 
> ```
>     for table_name in data:
>         table = data[table_name].copy()
>         data_container[table_name] = table[
>             table[year_column] > current_year - retention_period
>         ].copy()
> 
>         data_container[table_name] = table[
>             table[la_column].isin(signed_las)
>             ].copy()
> ```
> 
> Because data_container is re-referencing table.copy() for the signed_las check, it nullifies the result of the first check where it applies retention period.
> 
> By testing a modified json that should filter out 2020 files, you can see that it never does. But if you comment out lines 177-179, the code does then remove 2020 files.

Thanks Michael, I have pushed some changes now that should fix this. I did a quick end to end test and it looks like it's working as expected now.

2024-07-25 08:34 UTC, MichaelHanksSF approved these changes

2024-07-25 08:34 UTC, merged